steps:
  - name: 'gcr.io/$PROJECT_ID/webapp-stage1'
    entrypoint: yarn
    args: ['install']
    id: 'install'
  
  # Run check types
  - name: 'gcr.io/$PROJECT_ID/webapp-stage1'
    entrypoint: yarn
    args: ['check-types']
    wait_for: ['install']
  
  # Run check lint
  - name: 'gcr.io/$PROJECT_ID/webapp-stage1'
    entrypoint: yarn
    args: ['eslint:check']
    wait_for: ['install']
  
  # Run Test
  - name: 'gcr.io/$PROJECT_ID/webapp-stage1'
    entrypoint: yarn
    args: ['test-ci']
    wait_for: ['install']