steps:
    # Install packages
    - name: node
      entrypoint: npm
      args: ['ci']

    # Run check types
    - name: node
      entrypoint: npm
      args: ['run', 'check-types']

    # Run check lint
    - name: node
      entrypoint: npm
      args: ['run', 'eslint:check']
    
    # Run Test
    - name: node
      entrypoint: npm
      args: ['run', 'test-ci']