# This is a basic workflow to help you get started with Actions

name: gh-pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install package
        run: npm ci
      
      - name: Run test
        run: npm test
        
      - name: Run a multi-line script
        run: |
          npm run build
          npm run export
          
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.2
        with:
          # GitHub repository where assets will be deployed (default current)
          allow_empty_commit: false
          # Build directory to deploy
          build_dir: out
